# Workflow to check that modified files satisfy code quality requirements
name: Code Quality

# Controls when the workflow will run
on: 
  # Triggers the workflow on push and PRs
  push: 
  pull_request: 
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./"
          version: "~= 23.0"
