name: Code Style Check

# Controls when the workflow will run
on: 
  # Triggers the workflow on push and PRs
  push: 
  pull_request: 
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./"
          version: "~= 23.0"

      - name: Run autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .

      - name: Run isort
        uses: isort/isort-action@master

      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          ignore: F401
          args: "--verbose"
      

